[supervisord]
nodaemon=true

[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true
stdout_logfile=/var/log/supervisor/sshd.log
stderr_logfile=/var/log/supervisor/sshd_err.log

[program:postgres]
command=docker-entrypoint.sh postgres
autorestart=true
stdout_logfile=/var/log/supervisor/postgres.log
stderr_logfile=/var/log/supervisor/postgres_err.log
environment=POSTGRES_USER="%(ENV_POSTGRES_USER)",POSTGRES_PASSWORD="%(ENV_POSTGRES_PASSWORD)",POSTGRES_DB="%(ENV_POSTGRES_DB)"